import type { NextPage } from "next";
import { useSession } from "next-auth/react";
import Head from "next/head";
import { useState } from "react";
import CanvasDraw from 'react-canvas-draw'
import ColorIcon from "../components/ColorIcon";


const Home: NextPage = () => {
  const [color, setColor] = useState("#000000");
  const session = useSession({ required: true });
  let a;
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="drawer drawer-mobile">
        <input id="my-drawer-2" type="checkbox" className="drawer-toggle" />
        <div className="drawer-content flex flex-col items-center ">
          <h1 className="text-4xl font-bold mt-3 lg:pr-48">Anydraw</h1>
          <div className="p-3"></div>
          <div className="flex gap-6">
            <div className="border-2 border-black">
              <CanvasDraw canvasHeight={600} canvasWidth={600} hideGrid={true} brushColor={color} ref={a} />
            </div>
            <div>
              <div className="btn-group-vertical" role={"group"}>
                <div className="btn-group">
                  <button className="btn" onClick={() => setColor("#dc2626")}>
                    <ColorIcon colorHex="#dc2626" colorState={color} colorTailwind="bg-red-600" />
                  </button>
                  <button className="btn" onClick={() => setColor("#2563eb")}>
                    <ColorIcon colorHex="#2563eb" colorState={color} colorTailwind="bg-blue-600" />
                  </button>
                  <button className="btn" onClick={() => setColor("#16a34a")}>
                    <ColorIcon colorHex="#16a34a" colorState={color} colorTailwind="bg-green-600" />
                  </button>
                </div>
                <div className="btn-group">
                  <button className="btn" onClick={() => setColor("#000000")}>
                    <ColorIcon colorHex="#000000" colorState={color} colorTailwind="bg-black" />
                  </button>
                  <button className="btn" onClick={() => setColor("#7c3aed")}>
                    <ColorIcon colorHex="#7c3aed" colorState={color} colorTailwind="bg-violet-600" />
                  </button>
                  <button className="btn" onClick={() => setColor("#ea580c")}>
                    <ColorIcon colorHex="#ea580c" colorState={color} colorTailwind="bg-orange-600" />
                  </button>
                </div>
                <div className="btn-group">
                  <button className="btn" onClick={() => setColor("#eab308")}>
                    <ColorIcon colorHex="#eab308" colorState={color} colorTailwind="bg-yellow-500" />
                  </button>
                  <button className="btn" onClick={() => setColor("#f472b6")}>
                    <ColorIcon colorHex="#f472b6" colorState={color} colorTailwind="bg-pink-400" />
                  </button>
                  <button className="btn" onClick={() => setColor("#06b6d4")}>
                    <ColorIcon colorHex="#06b6d4" colorState={color} colorTailwind="bg-cyan-500" />
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className="drawer-side">
          <label htmlFor="my-drawer-2" className="drawer-overlay"></label>
          <ul className="menu p-4 overflow-y-auto w-80 bg-base-100 text-base-content">

            <li><a>Sidebar Item 1</a></li>
            <li><a>Sidebar Item 2</a></li>
          </ul>

        </div>
      </div>

    </>
  );
};


export default Home;
